config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :surveys
  match '/surveys/download', to: 'surveys#download', as: 'download', via: :post
  match "/users/update_privacy", to: "users#update_privacy", via: :post
  root 'dashboard#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  def score_and_id
    "#{id}-#{answer_score}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :section
  has_many :answers
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :questions
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_scores
  accepts_nested_attributes_for :survey_scores, allow_destroy: true
end

app/models/survey_score.rb
class SurveyScore < ApplicationRecord
  belongs_to :survey
  belongs_to :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index  	
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def new
    sections = Section.all.order('in_order ASC')
    @survey = Survey.new
    sections.each do |section|
      @survey.survey_scores.build(section_id: section.id)
    end
  end

  def create
    survey = Survey.new(survey_params)
    questions_and_answer_ids = JSON.parse(params.select{|x| x.starts_with?"question"}.to_json)
    questions_and_answer_ids.each do |k,v|
      survey.qanda[k.split("-").last] = v.split("-").first # using the id of each input, we get the question and answer id
    end
    if survey.save
      redirect_to survey_path(survey.id)
    else
      redirect_to new_survey_path
    end
  end

  def show
    @survey = Survey.find_by(id: params[:id])
    if @survey
      @survey_scores = SurveyScore.where(survey_id: @survey.id)
    else
      redirect_to root_path
    end
  end

  def download
    require 'csv'
    @survey = Survey.find_by(id: params[:id])
    if @survey
      csv = []
      csv << ["Results"]
      csv << ["Section", "Score"]
      @survey_scores = SurveyScore.where(survey_id: @survey.id).map do |score|
        if (0.01..1.99).include?(score.section_score.to_f)
          csv_score = "Green"
        elsif (2..2.99).include?(score.section_score.to_f)
          csv_score = "Yellow"
        else
          csv_score = "Red"
        end
        csv << ["#{score.section.id}. #{score.section.name}", csv_score]
      end
      csv << ['']
      csv << ["All Questions & Responses"]
      csv << ["Question", "Response"]
      @survey.qanda.each do |k,v|
        q = Question.find(k)
        a = Answer.find_by(id: v)
        answer_text = a ? a.answer_title : "Unanswered"
        csv << ["#{q.id}. #{q.question_title}",answer_text]
      end
      file = CSV.generate do |csv_file|
        csv.each do |f|
          csv_file << f
        end
      end
      send_data file, filename: "wac-survey-results.csv", disposition: 'attachment'
    end
  end

private
  def survey_params
    params.require(:survey).permit(:qanda, survey_scores_attributes: [:id, :survey_id, :section_id, :section_score])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def trim num
    i, f = num.to_i, num.to_f
    i == f ? i : f
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/dashboard/index.html.erb
<div class="main-content">
  <section class="landing">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
          <div class="landing__content">
            <h3 class='landing__content--title'>Welcome to the We All Count Data Biography Builder.</h3>
            <p class='landing__content--section'>This tool is designed around the Data Equity Biography checklist.  The tools helps you identify potential sources of bias in your dataset and gives you the chance to improve the equity in your use of the data.</p>
            <p class='landing__content--section'>This tool is designed to be used to assess the level of bias that is present in dataset. This is designed to assess the level of bias prior to analysis. To get a sense of the sources and locations of potential bias in your data most completely you’ll need the a copy of the survey tool that was used to collect the data, the codebook, and the document that tells you how the data was sampled and collected.</p>
            <%= link_to new_survey_path, class: 'landing__content--button' do %>
              <div class='landing__content--button-text'>
                Get Started
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/layouts/_footer.html.erb
<div class='footer'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1'>
        <%= image_tag('logo-white.png', class: 'footer__logo') %>
        <p class='footer__title'>Who Are We? </p>
        <p class='footer__text'>We All Count is a project dedicated to equity in data science. Read all about us <a href='https://weallcount.com/'>here.</a></p>
        <ul class='footer__icons'>
          <li class='social-icon'><a href='#'>Fb</a></li>
          <li class='social-icon'><a href='#'>Ig</a></li>
          <li class='social-icon'><a href='#'>Tw</a></li>
          <li class='social-icon'><a href='#'>Li</a></li>
        </ul>
      </div>
      <div class='col-md-2 col-sm-2'></div>
      <div class='col-md-4 col-sm-4'>
        <p class='footer__title'>How Does It Work?</p>
        <p class='footer__text'>Want to learn more about the process? Find out using the link below.</p>
        <p class='footer__title'>Speak To A Specialist</p>
        <p class='footer__text'>Would you like one of our specialists to get back to you with some expert advice on the potential bias in your dataset? If so, please click <a href='mailto:heather@idatassist.com'>here.</a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_hero.html.erb
<div class='hero'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-10 col-md-offset-1'>
        <%=image_tag('logo-white.png',class: 'hero__logo')%>
      </div>
    </div>
  </div>
  <div class='hero__text'>
    Dataset Bias Assessment Tool
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WacSurvey</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Barlow:400,500,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/hero'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
  <div class="section-block">
    <div class="tab-content">
      <%= render partial: "survey_scores", locals: {f: f} %>
    </div>
    <div class="submit-btn">
      <div class='survey__button-container'>
        <%= link_to 'Previous', "javascript:;", class: 'survey__button', id: 'previous' %>
        <%= link_to 'Next', "javascript:;", class: 'survey__button', id: 'next' %>
        <%= f.submit 'Submit', class: 'survey__button survey__button--submit', id: 'submit' %>
      </div>
    </div>
    <div class='survey__navigation'>
      <% 8.times do |i| %>
        <div class='survey__navigation--bar' data-nav-index=<%=i%>></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/surveys/_result.erb
<% section = Section.find_by(id: survey_score.section_id) %>
<div class="result-block">
  <div class="result-block__title" data-section-id=<%="#{section.id}."%>>
    <%= section.name %> 
  </div>
  <div class="result-block__result">
    <ul>
      <% section_score = survey_score.section_score%>
      <% if section_score.present? %>
        <% if section_score <= 1.99  %>
          <li class="is-green"></li> <%# green signal %>
          <li></li>
          <li></li>                         
        <% elsif (2..2.99).include?(section_score) %>
          <li></li> <%# yellow signal%>
          <li class="is-yellow"></li>
          <li></li>
        <% elsif section_score >= 2.999 %>
          <li></li> <%# red signal%>
          <li></li>
          <li class="is-red"></li>
        <% end %>
      <% else %>
        <li></li> <%# red signal%>
        <li></li>
        <li class="is-red"></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/surveys/_survey_scores.html.erb
<%= f.fields_for :survey_scores do |survey_score| %>
  <% section = survey_score.object.section %>
  <% if section.id == 1 %>
    <div class="tab-pane active" id="section-<%= section.id %>">
  <% else %>
    <div class="tab-pane" id="section-<%= section.id %>">
  <% end %>
    <%= survey_score.hidden_field :section_id %>
    <%= survey_score.hidden_field :section_score, id: "section_score-#{section.id}" %>
    <p class="survey__meta-data--title">
      <%= section.name %> 
    </p>
    <% questions = section.questions.order(:in_order) %>
    <% questions.each do |question|%>
      <div class="single-question-block">
        <h4 class="singleQuestion" data-number=<%=trim(question.serial_number)%>>
          <%= question.question_title %>
        </h4>
        <div class='survey__answers'>
          <%= collection_radio_buttons(:answer,
                                 question.id,
                                 question.answers,
                                 :score_and_id,
                                 :answer_title,
                                 { prompt: true },
                                 { class: 'form-control survey_section_score', name: "question-#{question.id}"}) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/surveys/_survey_section_tabs.html.erb
<ul class="tab-panel">
  <%= f.fields_for :survey_scores do |survey_score| %>
    <% section = survey_score.object.section %>
    <li>
      <a href="#section-<%= section.id %>" data-toggle="tab" data-section-id="<%= section.id %>" class="tab-btn"><%= section.id %></a>
    </li>
  <% end %>
</ul>

app/views/surveys/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <div class="survey">
        <div class="survey__meta-data">
          <div class="survey__meta-data--progress"> 
            Section <span id='progress-index'>1</span>/8
          </div>
        <%= render partial: "form" %>
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/surveys/new_old.html.erb
<header class="main-header inner-header">
  <div class="container">
    <%= image_tag('inner-header.jpg') %>
  </div>
</header>
<div class="main-content">
  <section class="survey-questions">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="logo">
            <%= image_tag('logo.png') %>
          </div>
        </div>
        <div class="col-md-8">
          <div class="start-here-content">
            <h1>Data Bias Assessment Tool ~Survey Edition</h1>
            <p>Answer the following questions about your dataset.</p>
            <p>We’ll show you your results once you’re complete</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="questions-block">
            <h2>Who - Questions about who the data was collected by and from</h2>
            <%= render partial: "form" %>
          </div>  
        </div>
      </div>
    </div>
  </section>
</div>

app/views/surveys/show.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
      <h3 class='result__title'>Summary of the results of assessment of potential bias in your dataset</h3>
      <br>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3'>
      <% @survey_scores.each do |survey_score| %>
        <%=render 'result', survey_score: survey_score %>
      <% end %> 
      <div class='results-download'>
        <%=link_to "Download", download_path(id: @survey.id), class: 'results-download__button', method: 'post'%>
        <h3 class='result__title'></h3>
      </div>
    </div>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="main-content">
  <section class="survey-summary">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 col-sm-2 col-sm-offset-2">
          <p class='landing__content--title'>Summary of the results of assessment of potential bias in your dataset</p>
          <div class="summary-chart">
            <div class='row'>
              <div class='col-md-12'>
                <% @survey_scores.each do |survey_score| %>
                  <% section = Section.find_by(id: survey_score.section_id) %>
                  <div class="summary-single-block">
                    <div class="summary-question">
                      <%= section.name %> 
                    </div>
                    <div class="summary-color">
                      <ul>
                        <% section_score = survey_score.section_score%>
                        <% if section_score.present? %>
                          <% if section_score <= 1.99  %>
                            <li class="is-green"></li> <%# green signal %>
                            <li></li>
                            <li></li>                         
                          <% elsif (2..2.99).include?(section_score) %>
                            <li></li> <%# yellow signal%>
                            <li class="is-yellow"></li>
                            <li></li>
                          <% elsif section_score >= 2.999 %>
                            <li></li> <%# red signal%>
                            <li></li>
                            <li class="is-red"></li>
                          <% end %>
                        <% else %>
                          <li></li> <%# red signal%>
                          <li></li>
                          <li class="is-red"></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/surveys/show_old.html.erb
<div class="main-content">
  <section class="survey-summary">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 col-sm-2 col-sm-offset-2">
          <p class='landing__content--title'>Summary of the results of assessment of potential bias in your dataset</p>
          <div class="summary-chart">
            <div class='row'>
              <div class='col-md-12'>
                <% @survey_scores.each do |survey_score| %>
                  <% section = Section.find_by(id: survey_score.section_id) %>
                  <div class="summary-single-block">
                    <div class="summary-question">
                      <%= section.name %> 
                    </div>
                    <div class="summary-color">
                      <ul>
                        <% section_score = survey_score.section_score%>
                        <% if section_score.present? %>
                          <% if section_score <= 1.99  %>
                            <li class="is-green"></li> <%# green signal %>
                            <li></li>
                            <li></li>                         
                          <% elsif (2..2.99).include?(section_score) %>
                            <li></li> <%# yellow signal%>
                            <li class="is-yellow"></li>
                            <li></li>
                          <% elsif section_score >= 2.999 %>
                            <li></li> <%# red signal%>
                            <li></li>
                            <li class="is-red"></li>
                          <% end %>
                        <% else %>
                          <li></li> <%# red signal%>
                          <li></li>
                          <li class="is-red"></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>